{% set name = "Flask-Webpack" %}
{% set version = "0.1.0" %}
{% set sha256 = "aa56bf97253a07e09514e2ff6ff67497d8654a66a17c208394687a64528ddc74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - flask

test:
  imports:
    - flask_webpack

about:
  home: https://github.com/nickjj/flask-webpack
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A Flask extension to manage assets with Webpack'

extra:
  recipe-maintainers:
    - mcs07
