travis:
  secure:
    BINSTAR_TOKEN: YIOVDyRBpKLdUZh89jZfzVXuyu7z+n7yTF867hiJL9OaaAWZhgWByrH0Oj2fwH9ckVkwnRYmlcMzJzawLxqkahWrfOmivJztgQlsX2D5dc3maWHyeDNe2gDKBRJZOLoWo5MVQXG3AtCWEWnyXWPvMtOctxYNup4+VcaaC73Cg/auENsK2ljTPOCgTqQ3F0Z2/txp0rhep+DfaLP5Z62elHvJhSFH+mY4fX1VPNF5MWTGFxWEIpYT2LsUHSXayj7TM2Mj3hEz+u9GYe61z1SRNbiIqxw0jcWvvMhEcWY8xxKASP8yVw5iy99NTA0uEEWVYjNA+V+qcSR7tqduyg6eM57LesQntOiB8n6Rm62fS1Atjgsk+pF+Eokm1C4pBlLVLIHlO6+zJM7EZIln7hUD+4pnEwHRYCan1/ujqksDT+Oc2VShzpPIEHIb7knOQDMU2cAzTQwzNUQpQJmtIwm2Hi0eTNeonY6ftpJgMbOFJYz4SHfpyhROmbyXkC1ilOQFnop1jwUaTDEKKjYrVrmUv+cHqKUvI+2lZwWAuKK2MMd+XHgj3iArvOvBjlm87UrubXSNJtbGSl+pqDodb1FZvZRtQejFFeBWJWCddb/DpqUR+YHxmNz8FyU2d7UE2z4UQneQXuqHPID6gpSv7C/Z9BYVO9gzeLE067ugd9rfTdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
