travis:
  secure:
    BINSTAR_TOKEN: paqx8P7Uedt9XzN6RrgdUlxt4PfFa26XRGMZqALHf3djWGDXr7AFtbSnO+EjFzP5oJE44RDUCs/oCtPXehGrlllQOo4crF933Fifq7bNpf6/M82thyaJeXR5uKVHGgHhqyrEbSK6fdG5LLPWS0uIvZfjMUZK5IXh4e/D3cM/prN8P/Es/LaYH/AOWK5SEV6q6YUxc95vUveOCnBqba49oFrX971gQHO6fBlWWut9gi21rhbJ9zDBW5X09AsyxHbR/ILyeu586JXwhjx2xL3Th9CAGUqf+bT2Dmq+X/aRospCKW4tesqcc5YfsfEkDCRRwVudezJcfAt7OLtnCBrm3KaLtzAdDApB6IwVDhf9WeTkVH8yaes9ZWduzZ8JtE+7LEfQjvKz8x7sksHjgEDgYlcBm+SxLTE8IkFQpONzdKflcuqtmBuSBuRRyu5DAX1lFQmTVLqnV+fsk9M9A1BktqYWf8moaf5p/H4isygu34vnHjMeG+yuX5kN90iL32Y8AwMceg3ynmF+WDeFQVShE/xKtAr8H+pvLQrzrioVU5qmT/fQ2KOYzA0CMb7lBYjNO2WkAoOjxoBSp0XVJvTsP+Z7VFxgC8cgmTVR3yr8YRTx/nmPYUThtnx9uEXE93NIjjG4sexSyh0pxpCCVlWGVUGSw4nfBNziLUFHNWnPSpE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
